POST http://localhost:5000/signin
Content-Type: application/json

{
    "email":"landry@gmail.com","password":"password"
}

###
POST http://localhost:5000/signup
Content-Type: application/json

{
    "email":"landry@gmail.com","password":"password1"
}

###
POST http://localhost:5000/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjQzMjM1MzJ9.e6mX4iNCNeFWaO9f6HbmQ2C6xIaygyIE4juGn4Litpk"
}

###
DELETE http://localhost:5000/signout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjQzMjM1MzJ9.e6mX4iNCNeFWaO9f6HbmQ2C6xIaygyIE4juGn4Litpk"
}
###
GET http://localhost:8000/test-connection
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjQzMjM2MDUsImV4cCI6MTYyNDMyNDIwNX0.OZxqwbHgJsB7dPgg-lt5zXsUftxwV-dQebZ2peoS7Og